import cookieParser from 'cookie-parser';
import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import { webhook } from './controllers/payment-controller.js';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middleware/error-handler.js';
import authRoutes from './routes/auth-routes.js';
import dashboardRoutes from './routes/dashboard-routes.js';
import paymentRoutes from './routes/payment-routes.js';
import promptRoutes from './routes/prompt-routes.js';
import uploadRoutes from './routes/upload-routes.js';
import { asyncHandler } from './utils/async-handler.js';

export const app = express();
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: env.CLIENT_URL, credentials: true, methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'] }));
app.post('/api/payments/webhook', express.raw({ type: 'application/json' }), asyncHandler(webhook));
app.use(express.json({ limit: '1mb' }), cookieParser());
app.use('/api/auth', rateLimit({ windowMs: 15 * 60 * 1000, limit: 100, standardHeaders: 'draft-8', legacyHeaders: false }), authRoutes);
app.use('/api/prompts', promptRoutes); app.use('/api/dashboard', dashboardRoutes); app.use('/api/payments', paymentRoutes); app.use('/api/uploads', uploadRoutes);
app.get('/api/health', (_request, response) => response.json({ status: 'ok' }));
app.use(notFound, errorHandler);
